# IP address to bind to
host = "0.0.0.0"
# Port to bind to
port = 25566
# Maximum number of players allowed on the server
max_players = 20
# Message of the day to display in the server list
motd = "Simple, performant, and reliable Limbo server\nfor Minecraft, written in Rust"
# Version to display in the server list
version = "Sculas/limbo-rs"
# Whether the limbo is behind Velocity and should use modern velocity forwarding
uses_velocity_modern = false
# If `uses_velocity_modern` is true, the secret to use for verifying Velocity forwarding
velocity_forwarding_secret = "<secret>"
# Whether the player's IP address should be withheld in the console
hide_player_ips = false
